"""adding synth table

Revision ID: a54582aa0c3f
Revises: b5d6d3fa51dc
Create Date: 2021-10-21 16:04:48.369335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54582aa0c3f'
down_revision = 'b5d6d3fa51dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('synth_name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('midi_ports', sa.String(length=10), nullable=True),
    sa.Column('synthesis_type', sa.String(length=50), nullable=True),
    sa.Column('voices', sa.String(length=5), nullable=True),
    sa.Column('file_type', sa.String(length=25), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synth')
    # ### end Alembic commands ###
